#node is a docker image from registry docker hub
#alpine is a lightweight linux distribution
FROM node:alpine

#copy all to app directory
COPY . /app

#set present working directory to app
WORKDIR /app

#run a linux command
CMD node app.js

